USE Tuan5;
GO
CREATE TABLE KHACHHANG (
    MAKHACHHANG INT PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(255),
    EMAIL NVARCHAR(100),
    DIENTHOAI NVARCHAR(20),
    FAX NVARCHAR(20)
);
GO
CREATE TABLE NHACUNGCAP (
    MACONGTY INT PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(255),
    DIENTHOAI NVARCHAR(20),
    FAX NVARCHAR(20),
    EMAIL NVARCHAR(100)
);
GO
CREATE TABLE NHANVIEN (
    MANHANVIEN INT PRIMARY KEY,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(255),
    DIENTHOAI NVARCHAR(20),
    LUONGCOBAN DECIMAL(18, 2),
    PHUCAP DECIMAL(18, 2)
);
GO
CREATE TABLE LOAIHANG (
    MALOAISANG INT PRIMARY KEY,
    TENLOAISANG NVARCHAR(100)
);
GO
CREATE TABLE MATHANG (
    MAHANG INT PRIMARY KEY,
    TENHANG NVARCHAR(100),
    MACONGTY INT,
    MALOAISANG INT,
    SOLUONG INT,
    DONVITINH NVARCHAR(20),
    GIAHANG DECIMAL(18, 2),
    FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    FOREIGN KEY (MALOAISANG) REFERENCES LOAIHANG(MALOAISANG)
);
GO
CREATE TABLE DONHANG (
    SOHOADON INT PRIMARY KEY,
    MAKHACHHANG INT,
    MANHANVIEN INT,
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(255),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);
GO
CREATE TABLE CHITIETDATHANG (
    SOHOADON INT,
    MAHANG INT,
    GIABAN DECIMAL(18, 2),
    SOLUONG INT,
    MUCGIAMGIA DECIMAL(5, 2),
    PRIMARY KEY (SOHOADON, MAHANG),
    FOREIGN KEY (SOHOADON) REFERENCES DONHANG(SOHOADON),
    FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);
GO
