USE Tuan6;
GO
CREATE TABLE KHACHHANG (
    MAKHACHHANG CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(200),
    EMAIL NVARCHAR(100),
    DIENTHOAI CHAR(15),
    FAX CHAR(15)
);
CREATE TABLE DONDATHANG (
    SOHOADON CHAR(10) PRIMARY KEY,
    MAKHACHHANG CHAR(10),
    MANHANVIEN CHAR(10),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(200)
);
CREATE TABLE NHANVIEN (
    MANHANVIEN CHAR(10) PRIMARY KEY,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(200),
    DIENTHOAI CHAR(15),
    LUONGCOBAN DECIMAL(18, 2),
    PHUCAP DECIMAL(18, 2)
);
CREATE TABLE CHITIETDATHANG (
    SOHOADON CHAR(10),
    MAHANG CHAR(10),
    GIABAN DECIMAL(18, 2),
    SOLUONG INT,
    MUCIGIAMGIA DECIMAL(5, 2),
    PRIMARY KEY (SOHOADON, MAHANG)
);
CREATE TABLE MATHANG (
    MAHANG CHAR(10) PRIMARY KEY,
    TENHANG NVARCHAR(100),
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(10),
    SOLUONG INT,
    DONVITINH NVARCHAR(50),
    GIAHANG DECIMAL(18, 2)
);
CREATE TABLE LOAIHANG (
    MALOAIHANG CHAR(10) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(100)
);
CREATE TABLE NHACUNGCAP (
    MACONGTY CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(200),
    DIENTHOAI CHAR(15),
    FAX CHAR(15),
    EMAIL NVARCHAR(100)
);
--thiết lập mối quan hệ giữa các bảng
ALTER TABLE DONDATHANG
	ADD CONSTRAINT FK_KHACHHANG_DONDATHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE DONDATHANG
	ADD CONSTRAINT FK_NHANVIEN_DONDATHANG FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);
ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_DONDATHANG_CHITIETDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON);
ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_MATHANG_CHITIETDATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG);
ALTER TABLE MATHANG
	ADD CONSTRAINT FK_NHACUNGCAP_MATHANG FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY);
ALTER TABLE MATHANG
	ADD CONSTRAINT FK_LOAIHANG_MATHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG);

