CREATE DATABASE Tuan6;
GO
USE Tuan6;
GO
CREATE TABLE KHACHHANG (
    MAKHACHHANG CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(200),
    EMAIL NVARCHAR(100) UNIQUE,
    DIENTHOAI CHAR(15) UNIQUE,
    FAX CHAR(15)
);
CREATE TABLE DONDATHANG (
    SOHOADON CHAR(10) PRIMARY KEY,
    MAKHACHHANG CHAR(10),
    MANHANVIEN CHAR(10),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(200)
);
CREATE TABLE NHANVIEN (
    MANHANVIEN CHAR(10) PRIMARY KEY,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(200),
    DIENTHOAI CHAR(15) UNIQUE,
    LUONGCOBAN MONEY,
    PHUCAP MONEY
);
CREATE TABLE CHITIETDATHANG (
    SOHOADON CHAR(10),
    MAHANG CHAR(10),
    GIABAN MONEY,
    SOLUONG INT,
    MUCIGIAMGIA MONEY,
    PRIMARY KEY (SOHOADON, MAHANG)
);
CREATE TABLE MATHANG (
    MAHANG CHAR(10) PRIMARY KEY,
    TENHANG NVARCHAR(100),
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(10),
    SOLUONG INT,
    DONVITINH NVARCHAR(50),
    GIAHANG MONEY
);
CREATE TABLE LOAIHANG (
    MALOAIHANG CHAR(10) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(100)
);
CREATE TABLE NHACUNGCAP (
    MACONGTY CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(100),
    TENGIAODICH NVARCHAR(100),
    DIACHI NVARCHAR(200),
    DIENTHOAI CHAR(15) UNIQUE,
    FAX CHAR(15),
    EMAIL NVARCHAR(100) UNIQUE
);
--thiết lập mối quan hệ giữa các bảng
ALTER TABLE DONDATHANG
	ADD CONSTRAINT FK_KHACHHANG_DONDATHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE DONDATHANG
	ADD CONSTRAINT FK_NHANVIEN_DONDATHANG FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);
ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_DONDATHANG_CHITIETDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON);
ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_MATHANG_CHITIETDATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG);
ALTER TABLE MATHANG
	ADD CONSTRAINT FK_NHACUNGCAP_MATHANG FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY);
ALTER TABLE MATHANG
	ADD CONSTRAINT FK_LOAIHANG_MATHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG);
--Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG  và bằng 0 cho cột MUCGIAMGIA trong bảng CHITIETDATHANG
ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT DF_CHITIETDATHANG_SOLUONG DEFAULT 1 FOR SOLUONG,
		CONSTRAINT DF_CHITIETDATHANG_MUCGIAMGIA DEFAULT 0 FOR MUCIGIAMGIA
--Bổ sung cho bảng DONDATHANG ràng buộc kiểm tra ngày giao hàng và ngày chuyển hàng phải sau hoặc bằng với ngày đặt hàng
ALTER TABLE DONDATHANG  
	ADD	CONSTRAINT DF_DONDATHANG_NGAYDATHANG DEFAULT GETDATE() FOR NGAYDATHANG,
		CONSTRAINT CK_DONDATHANG_NGAYGIAOHANG CHECK(NGAYGIAOHANG >= NGAYDATHANG),
		CONSTRAINT CK_DONDATHANG_NGAYCHUYENHANG CHECK(NGAYCHUYENHANG >= NGAYDATHANG);	
--Thiết lập ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể làm việc trong công ty khi đủ 18 tuổi và không quá 60 tuổi.
ALTER TABLE NHANVIEN
	ADD	CONSTRAINT CK_NGAYSINH_NV CHECK
			(NGAYSINH<=Dateadd(Year,-18,Getdate()) 
			AND  NGAYSINH>=Dateadd(Year,-60,Getdate()));
